server {
    listen 80;
    # 不暴露 Nginx 版本信息
    server_tokens off;
    server_name dev.single.xtechcn.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/dev.single.xtechcn.com;

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md) {
        return 404;
    }

    # 前端静态文件配置,去除路径中的 vue-admin-mro
   location ^~ /vue-admin-mro {
        rewrite "^/vue-admin-mro/(.*)$" /$1;
   }

    ############################# 服务配置开始 ################################

    # swagger 和 knife4j 配置
    location ~ ^(/v3/api-docs(/.*)?|/doc.html.*|/swagger-ui/.*|/webjars/.*)$ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://xtechcn-single-app;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 3600s;

        # 客户端真实 IP 传递到服务器
        proxy_set_header X-Real-IP $remote_addr;
        # 首先这个header并不是必需的，其次这个header host和proxy_pass转发产生的hostheader会出现冲突
        # 导致接口502的情况。但是这个配置更新后，nginx重启包括使用nginx -t进行测试也不会报错
        proxy_set_header Host $host;
        # 客户端或上一级端口
        proxy_set_header X-Real-Port $remote_port;
        # 请求协议配置,请求方式
        proxy_set_header X-Forwarded-Proto $scheme;
        # 包含了客户端和各级代理ip的完整ip链路
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 服务端请求反向代理配置
    location ~* ^/api/ {
        # 去掉最顶层的路径 /api/
        rewrite "^/api/(.*)$" /$1 break;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://xtechcn-single-single;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 3600s;

        # 客户端真实 IP 传递到服务器
        proxy_set_header X-Real-IP $remote_addr;
        # 首先这个header并不是必需的，其次这个header host和proxy_pass转发产生的hostheader会出现冲突
        # 导致接口502的情况。但是这个配置更新后，nginx重启包括使用nginx -t进行测试也不会报错
        proxy_set_header Host $host;
        # 客户端或上一级端口
        proxy_set_header X-Real-Port $remote_port;
        # 请求协议配置,请求方式
        proxy_set_header X-Forwarded-Proto $scheme;
        # 包含了客户端和各级代理ip的完整ip链路
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    ############################# 服务配置结束 ################################

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known {
        allow all;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$ {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
    access_log  /www/wwwlogs/dev.single.xtechcn.com.log;
    error_log  /www/wwwlogs/dev.single.xtechcn.com.error.log;
}

# 十一局开发环境
upstream xtechcn-single-app {
	# Alay 的服务
	server 192.168.1.23:9527;
	# 老田的地址
	server 192.168.1.131:9527;
	# 老周的地址
	server 192.168.1.192:9527;
}