# 服务器配置
server:
  port: ${SINGLE_APP_PORT:9527}

# 应用配置
spring:
  application:
    name: single-runner
  # 激活哪一个环境
  profiles:
    active: ${DEPLOY_ENV:dev}
    include:
      - mp
      - jdbc-ds
      - redis
      - swagger
      - antireplay
      - auth-default
      - base-default
